### PR TITLE
added message-timestamps to orderbook and symbol updates + callback for new messages

### PR DESCRIPTION
**Pull request by DerAlbiG**

### CODE REVIEW

**Comment by dextertd** [comment]
Thanks for your PR. Due to popular demand callbacks will be implemented, and I am currently working on this branch https://github.com/verata-veritatis/pybit/tree/restructure_wss

I do not understand the message timestamps? Can you explain why this is useful?

**Comment by DerAlbiG** [comment]
Hi,
My intention was to provide logging information.
Some messages are only sent when updated data is available.
For example consider the orderbook data. New data can arrive 10x per second. If you receive an orderbook update after some time of silence.. Which time does the update belong to? Was it the 4th or 6th update of the second?
If you want to write a datascaper with sub-second accuracy such things can matter.
Since pybit runs asynchronous, a timestamp should be directly attached to the data because later timestamp estimation may suffer from prcessing delays.
I admit that this is a pretty niche application but there is no cost to provide this data. On the other hand this timestamp is an eatimation after internet delays.. So it is inaccurate. But as long as bybit does not provide an accurate timestamp for the orderbook updates this is the next best thing.

**Comment by dextertd** [comment]
Ah got it, thanks. The restructure to use callbacks rather than polling `fetch()` on the aforementioned branch should solve this requirement, because the user's provided callback function will be instantly called upon the arrival of a new message. So, without having to make changes to the internal pybit code, the user could easily log the received time for every single update.

Due to this solutions being worked on separate, I would like to close this PR. Would you say that is reasonable? I appreciate your feedback, and it is certainly not alone - I have seen a few requests in https://t.me/BybitAPI asking for this feature.

**Comment by DerAlbiG** [comment]
I am ok if you close this request. I however think that bybit or pybit should somehow just provide the timestamps.. 
Your approach leads to unnecessary work on the users side to get "data about the data" so to speak. On the other hand it dies not pretend to provide server data that is created client-side. There is no right way here. 

I would prefere a server side solution since the timesteps are very inconsistent across the api.
Sometimes there arent timestamps, sometimes they are string-encoded, some are unix encoded down to milliseconds.
A unification to fractional unix time would seem to cover everything and it would be a good default content for every message.
But i know i am barking at the wrong tree here but you may have connections to the right people :-)

**Comment by dextertd** [comment]
Thanks for your feedback. 

> Your approach leads to unnecessary work on the users side to get "data about the data"

This is a reasonable criticism, and you're right - at the end of day there's no "right way"... I prefer a pybit which is closer to the original websocket.

>  But i know i am barking at the wrong tree here but you may have connections to the right people :-)

Not at all! I completely agree with your points about the API/websocket itself, and I have indeed already pushed for a more unified approach to timestamps returned. Your feedback is highly valued, and I think the theme of it (API inconsistency) is one felt by many.

**Pull request closed without merging**
